# Generated by Django 5.1.7 on 2025-04-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_password_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_token',
        ),
    ]
