# Generated by Django 5.1.7 on 2025-05-09 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role_adminprofile_authorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
