# Generated by Django 5.1.7 on 2025-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_authorprofile_approval_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='category_expertise',
            field=models.CharField(choices=[('News', 'News'), ('Politics', 'Politics'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Health', 'Health'), ('Science', 'Science'), ('Business', 'Business')], max_length=50),
        ),
    ]
