# Generated by Django 5.1.7 on 2025-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('published_at', models.DateTimeField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('source_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
