# Generated by Django 5.1.7 on 2025-05-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchednews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchednews',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fetchednews',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
