# Generated by Django 4.2.20 on 2025-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="source",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
