# Generated by Django 4.2.20 on 2025-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_article_title_alter_news_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
