# Generated by Django 5.1.7 on 2025-04-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_description_article_featured_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='featured',
        ),
    ]
