# Generated by Django 5.1.7 on 2025-05-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_add_default_categories'),
        ('news', '0004_remove_article_featured'),
    ]

    operations = [
    ]
